apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: index-observer
resources:
- ../../base
- monitor.yaml
replicas:
- name: index-observer
  count: 1
images:
- name: index-observer
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/index-observer/index-observer # {"$imagepolicy": "index-observer:index-observer:name"}
  newTag: 20220630132934-3d75d67cdcec4b5bf3b3e2eddd238b3fe8416e54 # {"$imagepolicy": "index-observer:index-observer:tag"}
