apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: index-observer
resources:
- ../../base
- monitor.yaml
replicas:
- name: index-observer
  count: 1
images:
- name: index-observer
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/index-observer/index-observer # {"$imagepolicy": "index-observer:index-observer:name"}
  newTag: 20220627142418-c4aff36e50778d207696f99a13cf5738d4312978 # {"$imagepolicy": "index-observer:index-observer:tag"}
