apiVersion: v1
kind: Service
metadata:
  labels:
    app: index-observer
  name: index-observer
  namespace: index-observer
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app: index-observer
  type: ClusterIP
